---
title: "Segment Analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Segment Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(alcyon)

lineStringMap <- st_read(
  system.file(
    "extdata", "testdata", "barnsbury", "barnsbury_small_axial.mif",
    package = "alcyon"
  ),
  geometry_column = 1L, quiet = TRUE
)
axialShapeGraph <- as(lineStringMap, "AxialShapeGraph")
shapeGraph <- axialToSegmentShapeGraph(
  axialShapeGraph,
  stubRemoval = 0.4
)
```

```{r}
segMap <- as(shapeGraph, "sf")
for (column in names(segMap)) {
  plot(segMap[, column])
}
```

```{r}
segmentResult <- allToAllTraverse(
  shapeGraph,
  radii = c("n", "200"),
  radiusTraversalType = TraversalType$Metric,
  traversalType = TraversalType$Angular,
  quantizationWidth = pi / 1024,
  includeBetweenness = FALSE
)
segMap <- as(shapeGraph, "sf")
for (column in segmentResult$newAttributes) {
  plot(segMap[, column])
}
```

```{r}
segmentResult <- allToAllTraverse(
  shapeGraph,
  radii = c("n", "100"),
  radiusTraversalType = TraversalType$Topological,
  traversalType = TraversalType$Topological,
  includeBetweenness = FALSE
)
segMap <- as(shapeGraph, "sf")
for (column in segmentResult$newAttributes) {
  plot(segMap[, column])
}
```

```{r}
segmentResult <- allToAllTraverse(
  shapeGraph,
  radii = c("n", "200"),
  radiusTraversalType = TraversalType$Metric,
  traversalType = TraversalType$Metric,
  includeBetweenness = FALSE
)
segMap <- as(shapeGraph, "sf")
for (column in segmentResult$newAttributes) {
  plot(segMap[, column])
}
```

```{r}
depthResult <- oneToAllTraverse(
  shapeGraph,
  traversalType = TraversalType$Topological,
  fromX = 530684,
  fromY = 184100.3
)

segMap <- as(shapeGraph, "sf")
for (column in depthResult$newAttributes) {
  plot(segMap[, column])
}
```

```{r}
depthResult <- oneToAllTraverse(
  shapeGraph,
  traversalType = TraversalType$Metric,
  fromX = 530684,
  fromY = 184100.3
)

segMap <- as(shapeGraph, "sf")
for (column in depthResult$newAttributes) {
  plot(segMap[, column])
}
```

```{r}
depthResult <- oneToAllTraverse(
  shapeGraph,
  traversalType = TraversalType$Angular,
  fromX = 530684,
  fromY = 184100.3,
  quantizationWidth = pi / 1024
)

segMap <- as(shapeGraph, "sf")
for (column in depthResult$newAttributes) {
  plot(segMap[, column])
}
```


