# SPDX-FileCopyrightText: Petros Koutsolampros
# SPDX-License-Identifier: GPL-3.0-only

#!/bin/bash

# Compile the Rcpp glue layer (src/*.cpp) with the project's warning set and
# report only diagnostics in our own code.
#
# The glue is compiled by R through src/Makevars, not by CMake, so the warning
# flags in src/libs/CMakeLists.txt never reach these files. salalib is checked
# by its own build; this script is how the glue gets the same treatment.
#
# Usage:
#   scripts/checkGlueWarnings.sh [compiler]
#
#   compiler     defaults to $CXX, or clang++
#   EXTRA_FLAGS  appended to the warning set, for ad-hoc checks
#
# RcppExports.cpp is skipped: it is generated by Rcpp::compileAttributes() and
# overwritten on every regeneration, so nothing in it is actionable. It is
# gitignored, so it is absent from a clean checkout and present in a working
# tree - skipping it explicitly keeps results the same either way.
#
# Exits 1 if anything is reported, so it works as a CI gate.

set -u

CXX_BIN="${1:-${CXX:-clang++}}"

cd "$(dirname "$0")/.." || exit 1
[ -d src ] || { echo "error: run from the package root" >&2; exit 1; }

# Mirrors the set in src/libs/salalib/CMakeLists.txt - keep the two in sync.
# This is a superset of the flags the stricter CRAN flavours use, so anything
# they would report is caught here first.
WARNINGS="-Wall -Wextra -Wpedantic -Wconversion -Wshadow \
-Wcast-align -Wpacked -Wsuggest-override -Wextra-semi \
-Wunused-macros -Wmissing-noreturn -Wmissing-declarations \
-Wold-style-cast -Weffc++ -Wpadded -Warray-bounds -Wdouble-promotion \
-Wno-float-equal -Wno-switch-enum -Wno-non-virtual-dtor -Wno-cast-qual \
-Wno-format-nonliteral -Wno-sign-conversion"

# Dependency headers go in with -isystem so their own warnings stay quiet -
# Rcpp alone emits well over a thousand conversion warnings.
RINC=$(R -s -e 'cat(R.home("include"))') || exit 1
RCPP=$(R -s -e 'cat(find.package("Rcpp"))')/include || exit 1
CLI=$(R -s -e 'cat(find.package("cli"))')/include || exit 1

echo "### $CXX_BIN"
echo "### $WARNINGS ${EXTRA_FLAGS:-}"
echo

out=$(for f in src/*.cpp; do
          case "${f##*/}" in RcppExports.cpp) continue ;; esac
          # shellcheck disable=SC2086
          "$CXX_BIN" -std=gnu++17 -fsyntax-only $WARNINGS ${EXTRA_FLAGS:-} \
              -Isrc -Isrc/libs \
              -isystem "$RINC" -isystem "$RCPP" -isystem "$CLI" \
              "$f" 2>&1
      done | grep -vE '/Rcpp/|/cli/|/R/include|/usr/(lib|include)/')

found=$(echo "$out" | grep -cE 'warning:|error:')
if [ "$found" -eq 0 ]; then
    echo "clean"
    exit 0
fi

echo "--- by category ---"
echo "$out" | grep -oE '\[-W[a-z0-9-]+\]' | sort | uniq -c | sort -rn
echo

echo "--- unique sites ---"
# Headers are included by several .cpp files, so the same site repeats.
echo "$out" | grep -E 'warning:|error:' \
    | sed -E 's|^(\./)?(src/)?([^:]+):([0-9]+):[0-9]+: (warning\|error): (.*)$|\3:\4  \6|' \
    | sort -u
echo

echo "--- $found diagnostics, $(echo "$out" | grep -E 'warning:|error:' \
    | sed -E 's/:[0-9]+:[0-9]+:.*//' | sort -u | wc -l) files ---"
exit 1
