# SPDX-FileCopyrightText: No Copyright
#
# SPDX-License-Identifier: CC0-1.0

name: Install and test on RDsan and RDcsan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  RDsan-RDAsan-build-and-test:
    runs-on: ubuntu-latest

    container: spatialnous/alcyon-debug:latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: RDsan, Install alcyon
        run: RDsan -e 'install.packages(".", repos=NULL)'
        # perhaps use devtools::build(".", binary = T, args = c("--preclean"))

      - name: RDsan, Test
        run: RDsan -e 'devtools::test(".")'

      - name: RDsan, Run examples
        run: RDsan -e 'devtools::run_examples(".")'

      - name: Clear for rebuild
        run: rm -rf 'src/build-Release'

      - name: RDcsan, Install alcyon
        run: RDcsan -e 'install.packages(".", repos=NULL)'

      - name: RDcsan, Test
        run: RDcsan -e 'devtools::test(".")'

      - name: RDcsan, Run examples
        run: RDcsan -e 'devtools::run_examples(".")'
