# SPDX-FileCopyrightText: No Copyright
#
# SPDX-License-Identifier: CC0-1.0

name: Install and test on RDsan and RDcsan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  RDsan-RDAsan-build-and-test:
    runs-on: ubuntu-latest

    container: spatialnous/alcyon-debug:latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: RDebug Makevars setup
        run: mkdir ~/.R/ && echo "PKG_LIBS += -fopenmp" > ~/.R/Makevars

      - name: RDsan, Install alcyon
        run: RDsan -e 'install.packages(".", repos=NULL)'

      - name: RDsan, Test
        run: RDsan -e 'testthat::test_dir("./tests")'

      - name: RDsan, Run examples
        run: RDsan -e 'devtools::run_examples(".")'

      - name: Clear for rebuild
        run: rm -rf 'src/build-Release'

      - name: RDcsan, Install alcyon
        run: RDcsan -e 'install.packages(".", repos=NULL)'

      - name: RDcsan, Test
        run: RDcsan -e 'testthat::test_dir("./tests")'

      - name: RDcsan, Run examples
        run: RDcsan -e 'devtools::run_examples(".")'
